export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";

export const FILTER_PRODUCTS_BY_BRAND = "FILTER_PRODUCTS_BY_BRAND";

export const FILTER_PRODUCTS_BY_REVIEWS = "FILTER_PRODUCTS_BY_REVIEWS";

export const SORT_PRODUCTS_BY_LOWTOHIGH = "SORT_PRODUCTS_BY_LOWTOHIGH";

export const SORT_PRODUCTS_BY_HIGHTOLOW = "SORT_PRODUCTS_BY_HIGHTOLOW";
